export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" },
];
export const APP_FEATURES = [
  {
    id: "01",
    title: "AI-Powered Q&A Generation",
    description:
      "Get relevant interview questions and answers instantly for any topic, generated by AI based on your search.",
  },
  {
    id: "02",
    title: "Topic-Based Search",
    description:
      "Search for specific subjects like React, Machine Learning, or System Design and receive focused questions and answers tailored to that topic.",
  },
  {
    id: "03",
    title: "Clear Answer Explanations",
    description:
      "Understand concepts better with simple, structured explanations provided alongside each answer.",
  },
  {
    id: "04",
    title: "Concept Breakdown on Demand",
    description:
      "Ask for deeper explanations of any topic and get easy-to-follow insights to strengthen your fundamentals.",
  },
  {
    id: "05",
    title: "Quick Interview Preparation",
    description:
      "Prepare efficiently by reviewing commonly asked questions and answers without unnecessary complexity.",
  },
];
