export const APP_FEATURES = [
  {
    id: "01",
    title: "AI-Powered Q&A Generation",
    description:
      "Get relevant interview questions and answers instantly for any topic, generated by AI based on your search.",
  },
  {
    id: "02",
    title: "Topic-Based Search",
    description:
      "Search for specific subjects like React, Machine Learning, or System Design and receive focused questions and answers tailored to that topic.",
  },
  {
    id: "03",
    title: "Clear Answer Explanations",
    description:
      "Understand concepts better with simple, structured explanations provided alongside each answer.",
  },
  {
    id: "04",
    title: "Concept Breakdown on Demand",
    description:
      "Ask for deeper explanations of any topic and get easy-to-follow insights to strengthen your fundamentals.",
  },
  {
    id: "05",
    title: "Quick Interview Preparation",
    description:
      "Prepare efficiently by reviewing commonly asked questions and answers without unnecessary complexity.",
  },
];
